INSERT INTO Ability VALUES ('Stench', 'By releasing a stench when attacking, the Pokémon may cause the target to flinch.');
INSERT INTO Ability VALUES ('Drizzle', 'The Pokémon makes it rain when it enters a battle.');
INSERT INTO Ability VALUES ('Speed Boost', 'The Pokémons Speed stat is boosted every turn.');
INSERT INTO Ability VALUES ('Battle Armor', 'Hard armor protects the Pokémon from critical hits.');
INSERT INTO Ability VALUES ('Sturdy', 'The Pokémon cannot be knocked out by a single hit as long as its HP is full. One-hit KO moves will also fail to knock it out.');
INSERT INTO Ability VALUES ('Damp', 'The Pokémon dampens its surroundings, preventing all Pokémon from using explosive moves such as Self-Destruct.');
INSERT INTO Ability VALUES ('Limber', 'The Pokémons limber body prevents it from being paralyzed.');
INSERT INTO Ability VALUES ('Sand Veil', 'Boosts the Pokémons evasiveness in a sandstorm.');
INSERT INTO Ability VALUES ('Static', 'The Pokémon is charged with static electricity and may paralyze attackers that make direct contact with it.');
INSERT INTO Ability VALUES ('Volt Absorb', 'If hit by an Electric-type move, the Pokémon has its HP restored instead of taking damage.');
INSERT INTO Ability VALUES ('Water Absorb', 'If hit by a Water-type move, the Pokémon has its HP restored instead of taking damage.');
INSERT INTO Ability VALUES ('Oblivious', 'The Pokémon is oblivious, keeping it from being infatuated, falling for taunts, or being affected by Intimidate.');
INSERT INTO Ability VALUES ('Cloud Nine', 'Eliminates the effects of weather.');
INSERT INTO Ability VALUES ('Compound Eyes', 'The Pokémons compound eyes boost its accuracy.');
INSERT INTO Ability VALUES ('Insomnia', 'The Pokémons insomnia prevents it from falling asleep.');
INSERT INTO Ability VALUES ('Color Change', 'The Pokémons type becomes the type of the move used on it.');
INSERT INTO Ability VALUES ('Immunity', 'The Pokémons immune system prevents it from being poisoned.');
INSERT INTO Ability VALUES ('Flash Fire', 'If hit by a Fire-type move, the Pokémon absorbs the flames and uses them to power up its own Fire-type moves.');
INSERT INTO Ability VALUES ('Shield Dust', 'Protective dust shields the Pokémon from the additional effects of moves.');
INSERT INTO Ability VALUES ('Own Tempo', 'The Pokémon sticks to its own tempo, preventing it from becoming confused or being affected by Intimidate.');
INSERT INTO Ability VALUES ('Suction Cups', 'The Pokémon uses suction cups to stay in one spot. This protects it from moves and items that would force it to switch out.');
INSERT INTO Ability VALUES ('Intimidate', 'When the Pokémon enters a battle, it intimidates opposing Pokémon and makes them cower, lowering their Attack stats.');
INSERT INTO Ability VALUES ('Shadow Tag', 'The Pokémon steps on the opposing Pokémons shadows to prevent them from fleeing or switching out.');
INSERT INTO Ability VALUES ('Rough Skin', 'The Pokémons rough skin damages attackers that make direct contact with it.');
INSERT INTO Ability VALUES ('Wonder Guard', 'Its mysterious power only lets supereffective moves hit the Pokémon.');
INSERT INTO Ability VALUES ('Levitate', 'By floating in the air, the Pokémon receives full immunity to all Ground-type moves.');
INSERT INTO Ability VALUES ('Effect Spore', 'Contact with the Pokémon may inflict poison, sleep, or paralysis on the attacker.');
INSERT INTO Ability VALUES ('Synchronize', 'If the Pokémon is burned, paralyzed, or poisoned by another Pokémon, that Pokémon will be inflicted with the same status condition.');
INSERT INTO Ability VALUES ('Clear Body', 'Prevents other Pokémons moves or Abilities from lowering the Pokémons stats.');
INSERT INTO Ability VALUES ('Natural Cure', 'The Pokémons status conditions are cured when it switches out.');
INSERT INTO Ability VALUES ('Lightning Rod', 'The Pokémon draws in all Electric-type moves. Instead of taking damage from them, its Sp. Atk stat is boosted.');
INSERT INTO Ability VALUES ('Serene Grace', 'Raises the likelihood of additional effects occurring when the Pokémon uses its moves.');
INSERT INTO Ability VALUES ('Swift Swim', 'Boosts the Pokémons Speed stat in rain.');
INSERT INTO Ability VALUES ('Chlorophyll', 'Boosts the Pokémons Speed stat in harsh sunlight.');
INSERT INTO Ability VALUES ('Illuminate', 'Raises the likelihood of meeting wild Pokémon by illuminating the surroundings.');
INSERT INTO Ability VALUES ('Trace', 'When it enters a battle, the Pokémon copies an opposing Pokémons Ability.');
INSERT INTO Ability VALUES ('Huge Power', 'Doubles the Pokémons Attack stat.');
INSERT INTO Ability VALUES ('Poison Point', 'Contact with the Pokémon may poison the attacker.');
INSERT INTO Ability VALUES ('Inner Focus', 'The Pokémons intense focus prevents it from flinching or being affected by Intimidate.');
INSERT INTO Ability VALUES ('Magma Armor', 'The Pokémons hot magma coating prevents it from being frozen.');
INSERT INTO Ability VALUES ('Water Veil', 'The Pokémons water veil prevents it from being burned.');
INSERT INTO Ability VALUES ('Magnet Pull', 'Prevents Steel-type Pokémon from fleeing by pulling them in with magnetism.');
INSERT INTO Ability VALUES ('Soundproof', 'Soundproofing gives the Pokémon full immunity to all sound-based moves.');
INSERT INTO Ability VALUES ('Rain Dish', 'The Pokémon gradually regains HP in rain.');
INSERT INTO Ability VALUES ('Sand Stream', 'The Pokémon summons a sandstorm when it enters a battle.');
INSERT INTO Ability VALUES ('Pressure', 'Puts other Pokémon under pressure, causing them to expend more PP to use their moves.');
INSERT INTO Ability VALUES ('Thick Fat', 'The Pokémon is protected by a layer of thick fat, which halves the damage taken from Fire- and Ice-type moves.');
INSERT INTO Ability VALUES ('Early Bird', 'The Pokémon awakens from sleep twice as fast as other Pokémon.');
INSERT INTO Ability VALUES ('Flame Body', 'Contact with the Pokémon may burn the attacker.');
INSERT INTO Ability VALUES ('Run Away', 'Enables a sure getaway from wild Pokémon.');
INSERT INTO Ability VALUES ('Keen Eye', 'The Pokémons keen eyes prevent its accuracy from being lowered.');
INSERT INTO Ability VALUES ('Hyper Cutter', 'The Pokémons prized, mighty pincers prevent other Pokémon from lowering its Attack stat.');
INSERT INTO Ability VALUES ('Pickup', 'The Pokémon may pick up an item another Pokémon used during a battle. It may pick up items outside of battle, too.');
INSERT INTO Ability VALUES ('Truant', 'Each time the Pokémon uses a move, it spends the next turn loafing around.');
INSERT INTO Ability VALUES ('Hustle', 'Boosts the Pokémons Attack stat but lowers its accuracy.');
INSERT INTO Ability VALUES ('Cute Charm', 'The Pokémon may infatuate attackers that make direct contact with it.');
INSERT INTO Ability VALUES ('Plus', 'Boosts the Sp. Atk stat of the Pokémon if an ally with the Plus or Minus Ability is also in battle.');
INSERT INTO Ability VALUES ('Minus', 'Boosts the Sp. Atk stat of the Pokémon if an ally with the Plus or Minus Ability is also in battle.');
INSERT INTO Ability VALUES ('Forecast', 'The Pokémon transforms with the weather to change its type to Water, Fire, or Ice.');
INSERT INTO Ability VALUES ('Sticky Hold', 'The Pokémons held items cling to its sticky body and cannot be removed by other Pokémon.');
INSERT INTO Ability VALUES ('Shed Skin', 'The Pokémon may cure its own status conditions by shedding its skin.');
INSERT INTO Ability VALUES ('Guts', 'Its so gutsy that having a status condition boosts the Pokémons Attack stat.');
INSERT INTO Ability VALUES ('Marvel Scale', 'The Pokémons marvelous scales boost its Defense stat if it has a status condition.');
INSERT INTO Ability VALUES ('Liquid Ooze', 'The strong stench of the Pokémons oozed liquid damages attackers that use HP-draining moves.');
INSERT INTO Ability VALUES ('Overgrow', 'Powers up Grass-type moves when the Pokémons HP is low.');
INSERT INTO Ability VALUES ('Blaze', 'Powers up Fire-type moves when the Pokémons HP is low.');
INSERT INTO Ability VALUES ('Torrent', 'Powers up Water-type moves when the Pokémons HP is low.');
INSERT INTO Ability VALUES ('Swarm', 'Powers up Bug-type moves when the Pokémons HP is low.');
INSERT INTO Ability VALUES ('Rock Head', 'Protects the Pokémon from recoil damage.');
INSERT INTO Ability VALUES ('Drought', 'Turns the sunlight harsh when the Pokémon enters a battle.');
INSERT INTO Ability VALUES ('Arena Trap', 'Prevents opposing Pokémon from fleeing from battle.');
INSERT INTO Ability VALUES ('Vital Spirit', 'The Pokémon is full of vitality, and that prevents it from falling asleep.');
INSERT INTO Ability VALUES ('White Smoke', 'The Pokémon is protected by its white smoke, which prevents other Pokémon from lowering its stats.');
INSERT INTO Ability VALUES ('Pure Power', 'Using its pure power, the Pokémon doubles its Attack stat.');
INSERT INTO Ability VALUES ('Shell Armor', 'A hard shell protects the Pokémon from critical hits.');
INSERT INTO Ability VALUES ('Air Lock', 'Eliminates the effects of weather.');
INSERT INTO Ability VALUES ('Tangled Feet', 'Boosts the Pokémons evasiveness if it is confused.');
INSERT INTO Ability VALUES ('Motor Drive', 'The Pokémon takes no damage when hit by Electric-type moves. Instead, its Speed stat is boosted.');
INSERT INTO Ability VALUES ('Rivalry', 'The Pokémons competitive spirit makes it deal more damage to Pokémon of the same gender, but less damage to Pokémon of the opposite gender.');
INSERT INTO Ability VALUES ('Steadfast', 'The Pokémons determination boosts its Speed stat every time it flinches.');
INSERT INTO Ability VALUES ('Snow Cloak', 'Boosts the Pokémons evasiveness in snow.');
INSERT INTO Ability VALUES ('Gluttony', 'If the Pokémon is holding a Berry to be eaten when its HP is low, it will instead eat the Berry when its HP drops to half or less.');
INSERT INTO Ability VALUES ('Anger Point', 'The Pokémon is angered when it takes a critical hit, and that maxes its Attack stat.');
INSERT INTO Ability VALUES ('Unburden', 'Boosts the Speed stat if the Pokémons held item is used or lost.');
INSERT INTO Ability VALUES ('Heatproof', 'The Pokémons heatproof body halves the damage taken from Fire-type moves.');
INSERT INTO Ability VALUES ('Simple', 'Doubles the effects of the Pokémons stat changes.');
INSERT INTO Ability VALUES ('Dry Skin', 'Restores the Pokémons HP in rain or when it is hit by Water-type moves. Reduces HP in harsh sunlight, and increases the damage received from Fire-type moves.');
INSERT INTO Ability VALUES ('Download', 'The Pokémon compares an opposing Pokémons Defense and Sp. Def stats before raising its own Attack or Sp. Atk stat—whichever will be more effective.');
INSERT INTO Ability VALUES ('Iron Fist', 'Powers up punching moves.');
INSERT INTO Ability VALUES ('Poison Heal', 'If poisoned, the Pokémon has its HP restored instead of taking damage.');
INSERT INTO Ability VALUES ('Adaptability', 'Powers up moves of the same type as the Pokémon.');
INSERT INTO Ability VALUES ('Skill Link', 'Maximizes the number of times multistrike moves hit.');
INSERT INTO Ability VALUES ('Hydration', 'Cures the Pokémons status conditions in rain.');
INSERT INTO Ability VALUES ('Solar Power', 'In harsh sunlight, the Pokémons Sp. Atk stat is boosted, but its HP decreases every turn.');
INSERT INTO Ability VALUES ('Quick Feet', 'Boosts the Speed stat if the Pokémon has a status condition.');
INSERT INTO Ability VALUES ('Normalize', 'All the Pokémons moves become Normal type. The power of those moves is boosted a little.');
INSERT INTO Ability VALUES ('Sniper', 'If the Pokémons attack lands a critical hit, the attack is powered up even further.');
INSERT INTO Ability VALUES ('Magic Guard', 'The Pokémon only takes damage from attacks.');
INSERT INTO Ability VALUES ('No Guard', 'The Pokémon employs no-guard tactics to ensure incoming and outgoing attacks always land.');
INSERT INTO Ability VALUES ('Stall', 'The Pokémon is always the last to use its moves.');
INSERT INTO Ability VALUES ('Technician', 'Powers up weak moves so the Pokémon can deal more damage with them.');
INSERT INTO Ability VALUES ('Leaf Guard', 'Prevents status conditions in harsh sunlight.');
INSERT INTO Ability VALUES ('Klutz', 'The Pokémon cant use any held items.');
INSERT INTO Ability VALUES ('Mold Breaker', 'The Pokémons moves are unimpeded by the Ability of the target.');
INSERT INTO Ability VALUES ('Super Luck', 'The Pokémon is so lucky that the critical-hit ratios of its moves are boosted.');
INSERT INTO Ability VALUES ('Aftermath', 'Damages the attacker if it knocks out the Pokémon with a move that makes direct contact.');
INSERT INTO Ability VALUES ('Anticipation', 'The Pokémon can sense an opposing Pokémons dangerous moves.');
INSERT INTO Ability VALUES ('Forewarn', 'When it enters a battle, the Pokémon can tell one of the moves an opposing Pokémon has.');
INSERT INTO Ability VALUES ('Unaware', 'When attacking, the Pokémon ignores the targets stat changes.');
INSERT INTO Ability VALUES ('Tinted Lens', 'The Pokémon can use "not very effective" moves to deal regular damage.');
INSERT INTO Ability VALUES ('Filter', 'Reduces the power of supereffective attacks that hit the Pokémon.');
INSERT INTO Ability VALUES ('Slow Start', 'For five turns, the Pokémons Attack and Speed stats are halved.');
INSERT INTO Ability VALUES ('Scrappy', 'The Pokémon can hit Ghost-type Pokémon with Normal- and Fighting-type moves. It is also unaffected by Intimidate.');
INSERT INTO Ability VALUES ('Storm Drain', 'The Pokémon draws in all Water-type moves. Instead of taking damage from them, its Sp. Atk stat is boosted.');
INSERT INTO Ability VALUES ('Ice Body', 'The Pokémon gradually regains HP in snow.');
INSERT INTO Ability VALUES ('Solid Rock', 'Reduces the power of supereffective attacks that hit the Pokémon.');
INSERT INTO Ability VALUES ('Snow Warning', 'The Pokémon makes it snow when it enters a battle.');
INSERT INTO Ability VALUES ('Honey Gather', 'The Pokémon may gather Honey after a battle.');
INSERT INTO Ability VALUES ('Frisk', 'When it enters a battle, the Pokémon can check an opposing Pokémons held item.');
INSERT INTO Ability VALUES ('Reckless', 'Powers up moves that have recoil damage.');
INSERT INTO Ability VALUES ('Multitype', 'Changes the Pokémons type to match the plate it holds.');
INSERT INTO Ability VALUES ('Flower Gift', 'Boosts the Attack and Sp. Def stats of the Pokémon and its allies in harsh sunlight.');
INSERT INTO Ability VALUES ('Bad Dreams', 'Damages opposing Pokémon that are asleep.');
INSERT INTO Ability VALUES ('Pickpocket', 'The Pokémon steals the held item from attackers that make direct contact with it.');
INSERT INTO Ability VALUES ('Sheer Force', 'Removes any additional effects from the Pokémons moves, but increases the moves power.');
INSERT INTO Ability VALUES ('Contrary', 'Reverses any stat changes affecting the Pokémon so that attempts to boost its stats instead lower them— and attempts to lower its stats will boost them.');
INSERT INTO Ability VALUES ('Unnerve', 'Unnerves opposing Pokémon and makes them unable to eat Berries.');
INSERT INTO Ability VALUES ('Defiant', 'If the Pokémon has any stat lowered by an opposing Pokémon, its Attack stat will be boosted sharply.');
INSERT INTO Ability VALUES ('Defeatist', 'Halves the Pokémons Attack and Sp. Atk stats when its HP drops to half or less.');
INSERT INTO Ability VALUES ('Cursed Body', 'May disable a move that has dealt damage to the Pokémon.');
INSERT INTO Ability VALUES ('Healer', 'Sometimes cures the status conditions of the Pokémons allies.');
INSERT INTO Ability VALUES ('Friend Guard', 'Reduces damage dealt to allies.');
INSERT INTO Ability VALUES ('Weak Armor', 'The Pokémons Defense stat is lowered when it takes damage from physical moves, but its Speed stat is sharply boosted.');
INSERT INTO Ability VALUES ('Heavy Metal', 'Doubles the Pokémons weight.');
INSERT INTO Ability VALUES ('Light Metal', 'Halves the Pokémons weight.');
INSERT INTO Ability VALUES ('Multiscale', 'Reduces the amount of damage the Pokémon takes while its HP is full.');
INSERT INTO Ability VALUES ('Toxic Boost', 'Powers up physical moves when the Pokémon is poisoned.');
INSERT INTO Ability VALUES ('Flare Boost', 'Powers up special moves when the Pokémon is burned.');
INSERT INTO Ability VALUES ('Harvest', 'May create another Berry after one is used.');
INSERT INTO Ability VALUES ('Telepathy', 'The Pokémon anticipates and dodges the attacks of its allies.');
INSERT INTO Ability VALUES ('Moody', 'Every turn, one of the Pokémons stats will be boosted sharply but another stat will be lowered.');
INSERT INTO Ability VALUES ('Overcoat', 'The Pokémon takes no damage from sandstorms. It is also protected from the effects of powders and spores.');
INSERT INTO Ability VALUES ('Poison Touch', 'May poison a target when the Pokémon makes contact.');
INSERT INTO Ability VALUES ('Regenerator', 'The Pokémon has a little of its HP restored when withdrawn from battle.');
INSERT INTO Ability VALUES ('Big Pecks', 'Prevents the Pokémon from having its Defense stat lowered.');
INSERT INTO Ability VALUES ('Sand Rush', 'Boosts the Pokémons Speed stat in a sandstorm.');
INSERT INTO Ability VALUES ('Wonder Skin', 'Makes status moves more likely to miss the Pokémon.');
INSERT INTO Ability VALUES ('Analytic', 'Boosts the power of the Pokémons move if it is the last to act that turn.');
INSERT INTO Ability VALUES ('Illusion', 'The Pokémon fools opponents by entering battle disguised as the last Pokémon in its Trainers party.');
INSERT INTO Ability VALUES ('Imposter', 'The Pokémon transforms itself into the Pokémon its facing.');
INSERT INTO Ability VALUES ('Infiltrator', 'The Pokémons moves are unaffected by the targets barriers, substitutes, and the like.');
INSERT INTO Ability VALUES ('Mummy', 'Contact with the Pokémon changes the attackers Ability to Mummy.');
INSERT INTO Ability VALUES ('Moxie', 'When the Pokémon knocks out a target, it shows moxie, which boosts its Attack stat.');
INSERT INTO Ability VALUES ('Justified', 'When the Pokémon is hit by a Dark-type attack, its Attack stat is boosted by its sense of justice.');
INSERT INTO Ability VALUES ('Rattled', 'The Pokémon gets scared when hit by a Dark-, Ghost-, or Bug-type attack or if intimidated, which boosts its Speed stat.');
INSERT INTO Ability VALUES ('Magic Bounce', 'The Pokémon reflects status moves instead of getting hit by them.');
INSERT INTO Ability VALUES ('Sap Sipper', 'The Pokémon takes no damage when hit by Grass-type moves. Instead, its Attack stat is boosted.');
INSERT INTO Ability VALUES ('Prankster', 'Gives priority to the Pokémons status moves.');
INSERT INTO Ability VALUES ('Sand Force', 'Boosts the power of Rock-, Ground-, and Steel-type moves in a sandstorm.');
INSERT INTO Ability VALUES ('Iron Barbs', 'The Pokémons iron barbs damage the attacker if it makes direct contact.');
INSERT INTO Ability VALUES ('Zen Mode', 'Changes the Pokémons shape when its HP drops to half or less.');
INSERT INTO Ability VALUES ('Victory Star', 'Boosts the accuracy of the Pokémon and its allies.');
INSERT INTO Ability VALUES ('Turboblaze', 'The Pokémons moves are unimpeded by the Ability of the target.');
INSERT INTO Ability VALUES ('Teravolt', 'The Pokémons moves are unimpeded by the Ability of the target.');
INSERT INTO Ability VALUES ('Aroma Veil', 'Protects the Pokémon and its allies from effects that prevent the use of moves.');
INSERT INTO Ability VALUES ('Flower Veil', 'Ally Grass-type Pokémon are protected from status conditions and the lowering of their stats.');
INSERT INTO Ability VALUES ('Cheek Pouch', 'The Pokémons HP is restored when it eats any Berry, in addition to the Berrys usual effect.');
INSERT INTO Ability VALUES ('Protean', 'Changes the Pokémons type to the type of the move its about to use. This works only once each time the Pokémon enters battle.');
INSERT INTO Ability VALUES ('Fur Coat', 'Halves the damage from physical moves.');
INSERT INTO Ability VALUES ('Magician', 'The Pokémon steals the held item from any target it hits with a move.');
INSERT INTO Ability VALUES ('Bulletproof', 'Protects the Pokémon from ball and bomb moves.');
INSERT INTO Ability VALUES ('Competitive', 'Boosts the Pokémons Sp. Atk stat sharply when its stats are lowered by an opposing Pokémon.');
INSERT INTO Ability VALUES ('Strong Jaw', 'The Pokémons strong jaw boosts the power of its biting moves.');
INSERT INTO Ability VALUES ('Refrigerate', 'Normal-type moves become Ice-type moves. The power of those moves is boosted a little.');
INSERT INTO Ability VALUES ('Sweet Veil', 'Prevents the Pokémon and its allies from falling asleep.');
INSERT INTO Ability VALUES ('Stance Change', 'The Pokémon changes its form to Blade Forme when it uses an attack move and changes to Shield Forme when it uses Kings Shield.');
INSERT INTO Ability VALUES ('Gale Wings', 'Gives priority to the Pokémons Flying-type moves while its HP is full.');
INSERT INTO Ability VALUES ('Mega Launcher', 'Powers up pulse moves.');
INSERT INTO Ability VALUES ('Grass Pelt', 'Boosts the Pokémons Defense stat on Grassy Terrain.');
INSERT INTO Ability VALUES ('Symbiosis', 'The Pokémon passes its held item to an ally that has used up an item.');
INSERT INTO Ability VALUES ('Tough Claws', 'Powers up moves that make direct contact.');
INSERT INTO Ability VALUES ('Pixilate', 'Normal-type moves become Fairy-type moves. The power of those moves is boosted a little.');
INSERT INTO Ability VALUES ('Gooey', 'Contact with the Pokémon lowers the attackers Speed stat.');
INSERT INTO Ability VALUES ('Aerilate', 'Normal-type moves become Flying-type moves. The power of those moves is boosted a little.');
INSERT INTO Ability VALUES ('Parental Bond', 'The parent and child attack one after the other.');
INSERT INTO Ability VALUES ('Dark Aura', 'Powers up the Dark-type moves of all Pokémon on the field.');
INSERT INTO Ability VALUES ('Fairy Aura', 'Powers up the Fairy-type moves of all Pokémon on the field.');
INSERT INTO Ability VALUES ('Aura Break', 'The effects of "Aura" Abilities are reversed to lower the power of affected moves.');
INSERT INTO Ability VALUES ('Primordial Sea', 'The Pokémon changes the weather to nullify Fire-type attacks.');
INSERT INTO Ability VALUES ('Desolate Land', 'The Pokémon changes the weather to nullify Water-type attacks.');
INSERT INTO Ability VALUES ('Delta Stream', 'The Pokémon changes the weather so that no moves are supereffective against the Flying type.');
INSERT INTO Ability VALUES ('Stamina', 'Boosts the Defense stat when the Pokémon is hit by an attack.');
INSERT INTO Ability VALUES ('Wimp Out', 'The Pokémon cowardly switches out when its HP drops to half or less.');
INSERT INTO Ability VALUES ('Emergency Exit', 'The Pokémon, sensing danger, switches out when its HP drops to half or less.');
INSERT INTO Ability VALUES ('Water Compaction', 'Boosts the Defense stat sharply when the Pokémon is hit by a Water-type move.');
INSERT INTO Ability VALUES ('Merciless', 'The Pokémons attacks become critical hits if the target is poisoned.');
INSERT INTO Ability VALUES ('Shields Down', 'When its HP drops to half or less, the Pokémons shell breaks and it becomes aggressive.');
INSERT INTO Ability VALUES ('Stakeout', 'Doubles the damage dealt to a target that has just switched into battle.');
INSERT INTO Ability VALUES ('Water Bubble', 'Lowers the power of Fire-type moves that hit the Pokémon and prevents it from being burned.');
INSERT INTO Ability VALUES ('Steelworker', 'Powers up Steel-type moves.');
INSERT INTO Ability VALUES ('Berserk', 'Boosts the Pokémons Sp. Atk stat when it takes a hit that causes its HP to drop to half or less.');
INSERT INTO Ability VALUES ('Slush Rush', 'Boosts the Pokémons Speed stat in snow.');
INSERT INTO Ability VALUES ('Long Reach', 'The Pokémon uses its moves without making contact with the target.');
INSERT INTO Ability VALUES ('Liquid Voice', 'Sound-based moves become Water-type moves.');
INSERT INTO Ability VALUES ('Triage', 'Gives priority to the Pokémons healing moves.');
INSERT INTO Ability VALUES ('Galvanize', 'Normal-type moves become Electric-type moves. The power of those moves is boosted a little.');
INSERT INTO Ability VALUES ('Surge Surfer', 'Doubles the Pokémons Speed stat on Electric Terrain.');
INSERT INTO Ability VALUES ('Schooling', 'When it has a lot of HP, the Pokémon forms a powerful school. It stops schooling when its HP is low.');
INSERT INTO Ability VALUES ('Disguise', 'Once per battle, the shroud that covers the Pokémon can protect it from an attack.');
INSERT INTO Ability VALUES ('Battle Bond', 'When the Pokémon knocks out a target, its bond with its Trainer is strengthened, and its Attack, Sp. Atk, and Speed stats are boosted.');
INSERT INTO Ability VALUES ('Power Construct', 'Cells gather to aid the Pokémon when its HP drops to half or less, causing it to change into its Complete Forme.');
INSERT INTO Ability VALUES ('Corrosion', 'The Pokémon can poison the target even if its a Steel or Poison type.');
INSERT INTO Ability VALUES ('Comatose', 'The Pokémon is always drowsing and will never wake up. It can attack while in its sleeping state.');
INSERT INTO Ability VALUES ('Queenly Majesty', 'The Pokémons majesty pressures opponents and makes them unable to use priority moves against the Pokémon or its allies.');
INSERT INTO Ability VALUES ('Innards Out', 'When the Pokémon is knocked out, it damages its attacker by the amount equal to the HP it had left before it was hit.');
INSERT INTO Ability VALUES ('Dancer', 'Whenever a dance move is used in battle, the Pokémon will copy the user to immediately perform that dance move itself.');
INSERT INTO Ability VALUES ('Battery', 'Powers up ally Pokémons special moves.');
INSERT INTO Ability VALUES ('Fluffy', 'Halves the damage taken from moves that make direct contact, but doubles that of Fire-type moves.');
INSERT INTO Ability VALUES ('Dazzling', 'The Pokémon dazzles its opponents, making them unable to use priority moves against the Pokémon or its allies.');
INSERT INTO Ability VALUES ('Soul-Heart', 'Boosts the Pokémons Sp. Atk stat every time another Pokémon faints.');
INSERT INTO Ability VALUES ('Tangling Hair', 'Contact with the Pokémon lowers the attackers Speed stat.');
INSERT INTO Ability VALUES ('Receiver', 'The Pokémon copies the Ability of a defeated ally.');
INSERT INTO Ability VALUES ('Power of Alchemy', 'The Pokémon copies the Ability of a defeated ally.');
INSERT INTO Ability VALUES ('Beast Boost', 'Boosts the Pokémons most proficient stat every time it knocks out a target.');
INSERT INTO Ability VALUES ('RKS System', 'Changes the Pokémons type to match the memory disc it holds.');
INSERT INTO Ability VALUES ('Electric Surge', 'Turns the ground into Electric Terrain when the Pokémon enters a battle.');
INSERT INTO Ability VALUES ('Psychic Surge', 'Turns the ground into Psychic Terrain when the Pokémon enters a battle.');
INSERT INTO Ability VALUES ('Misty Surge', 'Turns the ground into Misty Terrain when the Pokémon enters a battle.');
INSERT INTO Ability VALUES ('Grassy Surge', 'Turns the ground into Grassy Terrain when the Pokémon enters a battle.');
INSERT INTO Ability VALUES ('Full Metal Body', 'Prevents other Pokémons moves or Abilities from lowering the Pokémons stats.');
INSERT INTO Ability VALUES ('Shadow Shield', 'Reduces the amount of damage the Pokémon takes while its HP is full.');
INSERT INTO Ability VALUES ('Prism Armor', 'Reduces the power of supereffective attacks that hit the Pokémon.');
INSERT INTO Ability VALUES ('Neuroforce', 'Powers up the Pokémons supereffective attacks even further.');
INSERT INTO Ability VALUES ('Intrepid Sword', 'Boosts the Pokémons Attack stat the first time the Pokémon enters a battle.');
INSERT INTO Ability VALUES ('Dauntless Shield', 'Boosts the Pokémons Defense stat the first time the Pokémon enters a battle.');
INSERT INTO Ability VALUES ('Libero', 'Changes the Pokémons type to the type of the move its about to use. This works only once each time the Pokémon enters battle.');
INSERT INTO Ability VALUES ('Ball Fetch', 'If the Pokémon is not holding an item, it will fetch the Poké Ball from the first failed throw of the battle.');
INSERT INTO Ability VALUES ('Cotton Down', 'When the Pokémon is hit by an attack, it scatters cotton fluff around and lowers the Speed stats of all Pokémon except itself.');
INSERT INTO Ability VALUES ('Propeller Tail', 'Ignores the effects of opposing Pokémons Abilities and moves that draw in moves.');
INSERT INTO Ability VALUES ('Mirror Armor', 'Bounces back only the stat-lowering effects that the Pokémon receives.');
INSERT INTO Ability VALUES ('Gulp Missile', 'When the Pokémon uses Surf or Dive, it will come back with prey. When it takes damage, it will spit out the prey to attack.');
INSERT INTO Ability VALUES ('Stalwart', 'Ignores the effects of opposing Pokémons Abilities and moves that draw in moves.');
INSERT INTO Ability VALUES ('Steam Engine', 'Boosts the Speed stat drastically when the Pokémon is hit by a Fire- or Water-type move.');
INSERT INTO Ability VALUES ('Punk Rock', 'Boosts the power of sound-based moves. The Pokémon also takes half the damage from these kinds of moves.');
INSERT INTO Ability VALUES ('Sand Spit', 'The Pokémon creates a sandstorm when its hit by an attack.');
INSERT INTO Ability VALUES ('Ice Scales', 'The Pokémon is protected by ice scales, which halve the damage taken from special moves.');
INSERT INTO Ability VALUES ('Ripen', 'Ripens Berries and doubles their effect.');
INSERT INTO Ability VALUES ('Ice Face', 'The Pokémons ice head can take a physical attack as a substitute, but the attack also changes the Pokémons appearance. The ice will be restored when it snows.');
INSERT INTO Ability VALUES ('Power Spot', 'Just being next to the Pokémon powers up moves.');
INSERT INTO Ability VALUES ('Mimicry', 'Changes the Pokémons type depending on the terrain.');
INSERT INTO Ability VALUES ('Screen Cleaner', 'When the Pokémon enters a battle, the effects of Light Screen, Reflect, and Aurora Veil are nullified for both opposing and ally Pokémon.');
INSERT INTO Ability VALUES ('Steely Spirit', 'Powers up the Steel-type moves of the Pokémon and its allies.');
INSERT INTO Ability VALUES ('Perish Body', 'When hit by a move that makes direct contact, the Pokémon and the attacker will faint after three turns unless they switch out of battle.');
INSERT INTO Ability VALUES ('Wandering Spirit', 'The Pokémon exchanges Abilities with a Pokémon that hits it with a move that makes direct contact.');
INSERT INTO Ability VALUES ('Gorilla Tactics', 'Boosts the Pokémons Attack stat but only allows the use of the first selected move.');
INSERT INTO Ability VALUES ('Neutralizing Gas', 'While the Pokémon is in the battle, the effects of all other Pokémons Abilities will be nullified or will not be triggered.');
INSERT INTO Ability VALUES ('Pastel Veil', 'Prevents the Pokémon and its allies from being poisoned.');
INSERT INTO Ability VALUES ('Hunger Switch', 'The Pokémon changes its form, alternating between its Full Belly Mode and Hangry Mode after the end of every turn.');
INSERT INTO Ability VALUES ('Quick Draw', 'Enables the Pokémon to move first occasionally.');
INSERT INTO Ability VALUES ('Unseen Fist', 'If the Pokémon uses moves that make direct contact, it can attack the target even if the target protects itself.');
INSERT INTO Ability VALUES ('Curious Medicine', 'When the Pokémon enters a battle, it scatters medicine from its shell, which removes all stat changes from allies.');
INSERT INTO Ability VALUES ('Transistor', 'Powers up Electric-type moves.');
INSERT INTO Ability VALUES ('Dragons Maw', 'Powers up Dragon-type moves.');
INSERT INTO Ability VALUES ('Chilling Neigh', 'When the Pokémon knocks out a target, it utters a chilling neigh, which boosts its Attack stat.');
INSERT INTO Ability VALUES ('Grim Neigh', 'When the Pokémon knocks out a target, it utters a terrifying neigh, which boosts its Sp. Atk stat.');
INSERT INTO Ability VALUES ('As One', 'This Ability combines the effects of both Calyrexs Unnerve Ability and Glastriers Chilling Neigh Ability.');
INSERT INTO Ability VALUES ('Sharpness', 'Powers up slicing moves.');
INSERT INTO Ability VALUES ('Soul Heart', 'Boosts its Sp. Atk stat every time a Pokémon faints.');
